[versions]
agp = "9.0.0"
androidx-activity = "1.12.2"
androidx-lifecycle = "2.9.6"
coil = "3.3.0"
componentsResources = "1.10.0"
composeMultiplatform = "1.10.0"
credentials = "1.5.0"
foundation = "1.10.0"
googleid = "1.1.1"
kotlin = "2.3.0"
composeNavigation = "2.9.1"
appcompat = "1.7.1"
kotlinxDatetime = "0.7.1"
logging = "2.1.0"
material3 = "1.9.0"
runtime = "1.10.0"
supabasekt = "3.3.0"
ktor = "3.3.3"
generativeaiGoogle = "0.9.0-1.1.0"
buildkonfigGradlePlugin = "0.17.1"
koin-bom = "4.1.1"
ui = "1.10.0"
uiToolingPreview = "1.10.0"

[libraries]
androidx-credentials = { module = "androidx.credentials:credentials", version.ref = "credentials" }
androidx-credentials-play-services-auth = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "credentials" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
googleid = { module = "com.google.android.libraries.identity.googleid:googleid", version.ref = "googleid" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-lifecycle-viewmodelCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtimeCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
compose-navigation = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "composeNavigation" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }

# Compose
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "runtime" }
compose-ui-tooling-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "uiToolingPreview" }
compose-components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "componentsResources" }
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "foundation" }
compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "material3" }
compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "ui" }

# Supabase
logging = { module = "com.diamondedge:logging", version.ref = "logging" }
supabasekt-bom = { module = "io.github.jan-tennert.supabase:bom", version.ref = "supabasekt" }
supabasekt-postgrest = { module = "io.github.jan-tennert.supabase:postgrest-kt" }
supabasekt-auth = { module = "io.github.jan-tennert.supabase:auth-kt" }
supabasekt-compose-auth = { module = "io.github.jan-tennert.supabase:compose-auth" }
supabasekt-compose-auth-ui = { module = "io.github.jan-tennert.supabase:compose-auth-ui" }
supabasekt-realtime = { module = "io.github.jan-tennert.supabase:realtime-kt" }

# Ktor
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }

# Koin
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin-bom" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-compose = { module = "io.insert-koin:koin-compose" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel" }
koin-compose-viewmodel-navigation = { module = "io.insert-koin:koin-compose-viewmodel-navigation" }

# Gen AI
generativeai-google = { module = "dev.shreyaspatil.generativeai:generativeai-google", version.ref = "generativeaiGoogle" }

# BuildKonfig
buildkonfig-gradle-plugin = { module = "com.codingfeline.buildkonfig:buildkonfig-gradle-plugin", version.ref = "buildkonfigGradlePlugin" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
androidKmpLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
cmp = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kmp = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
