name: Deploy to Firebase Distribution

on:
  push:
    branches:
      - main

jobs:
  distribute:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 23
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '23'

      - name: Setup Ruby (for Fastlane)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.0'
          bundler-cache: true

      - name: Create local.properties
        run: |
          echo "" >> local.properties
          echo "google_auth_client_id=${{ secrets.GOOGLE_AUTH_CLIENT_ID }}" >> local.properties
          echo "supabase.project_url=${{ secrets.SUPABASE_PROJECT_URL }}" >> local.properties
          echo "supabase.public_api_key=${{ secrets.SUPABASE_PUBLIC_API_KEY }}" >> local.properties
          echo "gemini.api_key=${{ secrets.GEMINI_API_KEY }}" >> local.properties
          echo "keystore.password=${{ secrets.KEYSTORE_PASSWORD }}" >> local.properties
          echo "keystore.alias=${{ secrets.KEYSTORE_ALIAS }}" >> local.properties
          echo "keystore.alias_password=${{ secrets.KEYSTORE_ALIAS_PASSWORD }}" >> local.properties

      - name: Retrieve google-services.json
        run: |
          echo "${{ secrets.GOOGLE_SERVICE_JSON }}" | base64 --decode > android-app/google-services.json

      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build and Deploy with Fastlane
        env:
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          cd android-app
          bundle install
          bundle exec fastlane distribute